In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import ast
import datetime
%matplotlib inline

In [ ]:
def clean_df(df_raw) :
    df = df_raw.copy()
    df['main_category'] = df['category'].apply(
        lambda x: ast.literal_eval(x)['slug'].split('/')[0]
    )

    df['successful'] = pd.Series(df['goal'] <= df['converted_pledged_amount'],dtype=np.int8)
    df.drop(columns=['goal','converted_pledged_amount'],inplace=True)

    unix_cols = ['launched_at','deadline','state_changed_at']
    for col in unix_cols :
        df[col] = pd.to_datetime(df[col],origin='unix')

    scrape_date = datetime.datetime(2020,9,17)
    df = df[df['deadline'] < scrape_date]
    df['deadline'] = (df['deadline'] - df['launched_at']).dt.days

    drop_cols = ['blurb','country','creator','currency_symbol','current_currency',
                'country_displayable_name','creator','location','photo',
                'profile','slug','source_url','urls','is_backing','is_starred',
                'static_usd_rate','usd_pledged','usd_type','category','friends',
                 'permissions','created_at', 'currency_trailing_code']
    to_datetime_cols = []
    to_ord_cols = []
    to_one_hot_cols = ['currency']

    df.drop(columns=drop_cols,inplace=True)

    
    
    for col in to_datetime_cols :
        df[col] = pd.to_datetime(df[col],origin='unix')
    
    for col in to_one_hot_cols:
        one_hot = pd.get_dummies(df[col],prefix=col,drop_first=True)
        df = df.join(one_hot)
    df.drop(columns=to_one_hot_cols,inplace=True)

    mid = df['name']
    df.drop(labels=['name'], axis=1, inplace = True)
    df.insert(0, 'name', mid)

    return df

In [ ]:
data = pd.read_csv('Kickstarter.csv')
df = clean_df(data)
df.head()

                                                name  ...  currency_USD
0                       pulsing orange, skinny youth  ...             1
1     Help Tony Copeland and get free cd's and mp3's  ...             1
2  Public Screen Printing at the 2013 Presidentia...  ...             1
3  Help built your magical rainsforest holiday st...  ...             1
4     B. collective: locally made fine art and gifts  ...             1

[5 rows x 28 columns]